config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top/main'
  post 'top/login'

  root 'top#main'
  get 'top/logout'
  resources :users, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, uniqueness: true
    def self.authenticate(uid, pass)
        user = User.find_by(uid: uid)
        if   user and BCrypt::Password.new(user.pass) == pass
             User
        else
             nil
           
        end 
     
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid]
           render 'main'
           
        else
           render 'login'
        end
    end
    def login
        logger.debug('******************'+params[:uid]+params[:pass])
        user = User.authenticate(params[:uid], params[:pass])
        if user
 
               session[:login_uid] = params[:uid]
               redirect_to top_main_path

        else
            render 'error'
        end
    end
    
    def logout
        session.delete(:login_uid)
        @user = nil
        flash[:notice] = "ログアウトしました。"
        redirect_to top_main_path
        
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def new
        @user = User.new
    end
    def create
         pass = BCrypt::Password.create(params[:user][:pass])
         @user = User.new(uid: params[:user][:uid], pass: pass)
        if @user.save
            
            flash[:success] = "登録完了"
            redirect_to users_path
        else
            flash[:failed] = "登録失敗"
            render 'new'
        end
    end
    def destroy 
        user = User.find(params[:id])
        user.destroy
            flash[:destroy] = "削除しました。"
        redirect_to users_path, flash: {destroy:  "ツイートを削除しました。"}
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<p><font color="green">ログイン失敗</font></p>

<%= link_to 'Back', top_main_path %>

app/views/top/login.html.erb
<h2>ログイン画面</h2>
<% if flash[:notice] %>
  <p><font color="blue"><%= flash[:notice] %></font></p>
<% end %>  
<%= form_tag '/top/login', method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag 'ログイン' %>
<% end %>  
<%= link_to "新規登録", new_user_path %>
<%= link_to "ユーザー情報", users_path %>

app/views/top/main.html.erb
<h2>MY PAGE</h2>
<p><font color="blue">ログイン中です</font></p>

<%= link_to "ログアウト", top_logout_path %>

app/views/users/index.html.erb
<h2>ユーザー</h2>

<% @users.each do |user| %>
 <p>
     <%= user.uid %>
     <%= user.pass %>
     <%= link_to 'delete', user, method: :delete %>
 </p>
<% end %>
<%= link_to "ログイン", top_main_path %>

<%= link_to "新規登録", new_user_path %>

app/views/users/new.html.erb
<h2>新規登録画面</h2>
<%= form_for @user do |form| %>
 <%= form.label :uid, "ユーザーID" %>
 <%= form.text_field :uid %>
 <%= form.label :pass, "パスワード" %>
 <%= form.password_field :pass %>
 <%= form.submit "登録" %>
<% end %>

<%= link_to 'Back', users_path %>